
on: push

jobs:


  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.30.0'
      - run: |
          make all_checks

  generate: 
    runs-on: ubuntu-latest
    needs: validate

    steps:      
      - name: Generate
        run: |
            make generate

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: generate

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@4 # or specific "vX.X.X" version tag for this action
        with:
          site-directory: ./out
          target-branch: gh-pages
          commit-message: Deploy site
          publish-token: ${{ secrets.GITHUB_TOKEN }}