
on: push

permissions:
  contents: write

jobs:


  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.30.0'
      - run: |
          make all_checks

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: validate

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      contents: write   

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate
        run: |
            make generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: releases